---
# Launch instance, runs some tasks and then terminate them
-
  hosts: all
  connection: local
  gather_facts: False


#  vars_files:
    # Include Relative Path file
    #- /etc/ansible/group_vars/windows.yml

  vars:
    servername: prdcuse1004
    profile: dev
    key_name: SimonCummings
    instance_type: t2.small
    security_group: sg-e729bd9d
    image: ami-9fcfb688 # Windows 2012 R2v2
    region: us-east-1
    subnet: subnet-45e7340c

  tasks:
    - name: Provision Instance
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        profile: "{{ profile }}"
        vpc_subnet_id: "{{ subnet }}"
        exact_count: 1
        count_tag:
          Owner: "simon_cummings"
          Name: windows-simon_ansible_test
          Project: "ES_PCM"
        instance_tags:
          Owner: "simon_cummings"
          OwnerEmail: "DL-ESP-ServiceDesign-AWS@symantec.com"
          ApplicationRole: "Windows - via Ansible"
          Name: "{{ servername }}"
          Project: "ES_PCM"
          BusinessUnit: "Enterprise Security"
        #monitoring: no
        #|assign_public_ip: yes
      register: ec2
